### ISSUE TITLE
Interpolator support?

### ISSUE THREAD

**Issue by dokiKit** [mikepenz/ItemAnimators#10]
Great library. Does it support interpolator? I don't see setter of interpolator available in the item animators. 

Best regards

**Comment by saket** [comment]
The function you're looking for is called `withInterpolator()`

https://github.com/mikepenz/ItemAnimators/blob/dacfdbd7bfe8a281670e9378a74f54e362678c43/library/src/main/java/com/mikepenz/itemanimators/BaseItemAnimator.java#L110
