### ISSUE TITLE
how to animate on item at a time instead of all together?

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/ItemAnimators#9]
hi.
i have an `ArrayList<> items;` of my items and i do `adapter.add(items)`.
at the moment the items are animated all together as if it was a single chunk. what i would like to have is for the items to be animated one at a time so it looks like they are being added one right after the other and for each item to be animated individually.
i tried this
 ```
for (int i = 0; i < items.size(); i++)
 {
    mAdapter.add(items.get(i));
    mAdapter.notifyAdapterItemInserted(i);
}
```

but still the entire list is being animated as a single chunk.

how can i achieve one-at-a-time animation??

**Comment by mikepenz** [comment]
This library is meant to provide the default item animator behaviour defined by the `RecyclerView` 

If you want to have animating one by one and after each other and animating while scrolling you'd need to use a different library which will basically work via animations defined in the adapter. (ItemAnimator's are not meant to do this ;))

**Comment by or-dvir** [comment]
ok thanks
